name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust target
        run: |
          rustup target add aarch64-linux-android

      - name: Build
        env:
          CC_aarch64_linux_android: ${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: ${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
        run: |
          cargo build --release --target aarch64-linux-android

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: libncore
          path: target/aarch64-linux-android/release/*.so

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ncore
          path: |
            target/aarch64-linux-android/release/ncore